build:
  cuda_version: "12.1.1"
  python_packages:
    - accelerate==1.0.1
    - transformers==4.43.4
    - diffusers==0.31.0
    - torch==2.4.0
    - protobuf==3.20.1
    - sentencepiece==0.2.0
    - inferless==0.2.6
    - pydantic==2.10.2